### ISSUE TITLE
Cofactor + two letter chain identifier = bug in eppic

### ISSUE THREAD

**Issue by kumar-physics** [eppic-team/eppic#29] opened 2014-12-19 10:35 UTC
We thought that the mega entries with multiple character chain identifier are having problems ONLY while uploading and EPPIC calculations and the interface information is fine. This is not true. EPPIC calculations may also go wrong because of the ambiguity in the chain identifier. 
Examples:
4v4c,4v4d,4v4e,4v59,4v6m

The above entries didn't produce any notable error(java error), but  will run for long time and get stuck while creating PyMOL files.    

![4v4c_2](https://cloud.githubusercontent.com/assets/5636184/5503076/d8ea9774-8772-11e4-94a7-5412f5ca5096.png)

In the example case 4v4c interface 2 the cofactors are far away from the interface as a result of chain ambiguity

**Comment by josemduarte** [comment] 2015-02-19 13:53
This seems to be happening because there are more than 100,000 atoms in the structure: when the PDB file is written numbers go to the wrong columns and pymol doesn't digest that so well as seen above

This is related to the new mmCIF large enries. We'll close this one and keep the main issue #38 open

**Comment by josemduarte** [comment] 2015-02-26 15:38
Will close this as a duplicate of #23

**Closed by josemduarte** 2015-02-26 15:38 UTC
Labels: bug
