### ISSUE TITLE
Asymmetric unit with multiple copies of same chain may produce wrong interface 

### ISSUE THREAD

**Issue by kumar-physics** [eppic-team/eppic#38] opened 2015-02-19 13:23 UTC
4v4c,4v4d and 4v4d  are the pdb entries having strange asymmetric unit with multiple copies of same chains. EPPIC calculations for those entries were struck, when it tries to generate pymol images. The reason is those are not proper interfaces 
![4v4d_1](https://cloud.githubusercontent.com/assets/5636184/6267264/b941b492-b842-11e4-8cc9-b5f93f1a4d02.png)

I think we have seen similar artifacts in a different situation. I am not sure whether its related to this.

**Comment by kumar-physics** [comment] 2015-02-19 13:27
4v59 also add having similar problem

**Comment by josemduarte** [comment] 2015-02-19 13:52
This seems to be happening because there are more than 100,000 atoms in the structure: when the PDB file is written numbers go to the wrong columns and pymol doesn't digest that so well as seen above

This is a duplicate of #29 , closing it

**Closed by josemduarte** 2015-02-19 13:52 UTC
