### ISSUE TITLE
Problem in loading NMR entries. 

### ISSUE THREAD

**Issue by kumar-physics** [eppic-team/eppic#120] opened 2016-06-02 20:02 UTC
When I try to load NMR pdb entries, first one works fine, but the second one hangs. 
Steps to reproduce the error

1. First load 2n2r
then click home and enter 2e2f
 Then this will take ever to load. But if you open another tab it will be there, again if you switch between entries it will hang. 
 
I tried in a linux desktop and mac, the result is the same.

**Comment by josemduarte** [comment] 2016-06-02 20:36
Good catch! I've tried it and I can reproduce the problem in 2.1.2. But in 3.0-alpha it works fine! So somehow it has been fixed as we moved to 3.0... I have no idea what fixed it though. Anyway good to have a record of the issue here.

**Comment by gcapitani** [comment] 2016-06-03 09:57
Thanks @kumar-physics! In 2.1.2 a refresh actually allows the second entry to be loaded. Great that the problem does not happen in 3.0-alpha.

**Comment by josemduarte** [comment] 2016-06-03 21:28
I'll close this, since it seems to be working fine in dev.

**Closed by josemduarte** 2016-06-03 21:28 UTC
Labels: bug
